### ISSUE TITLE
Odd text alignment for integration icons with longer text

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/docs-old#37]
### Issue Summary

Integrations with descriptions that wrap end up with odd text alignment.

<img width="434" alt="screenshot 2018-11-08 at 11 10 58" src="https://user-images.githubusercontent.com/415/48195448-95310100-e347-11e8-84d1-b53fac5610f8.png">

### To Reproduce

1. Open the homepage, look at the Google Analytics integration icon

Tested in latest Safari and Chrome

**Comment by Neatoro** [comment]
I opened a pull request for that issue. It should fix it for all sizes.
