### ISSUE TITLE
Documentation on static sites

### ISSUE THREAD

**Issue by m1guelpf** [TryGhost/docs-old#39]
Now that we have rebuild webhooks, it'd be interesting to add a Tutorial explaining how to build a static site that auto updates on Ghost content updates. I'd love to help on this if you can point me in the right direction :)

**Comment by kymellis** [comment]
@m1guelpf thanks for the suggestion :) 

We're still working on this at the moment and will release more information about using alternative front ends with Ghost. We'll definitely be publishing tutorials about this too! 

In the meantime, there is some further information [here](https://docs.ghost.org/api/gatsby/).
