### ISSUE TITLE
404 page is broken

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/docs-old#44]
### Issue Summary

After landing on the 404 page it's not possible to use any of the links to get away from the 404 page.

### To Reproduce

1. Open a non-existant URL, I hit when I noticed the problem https://docs.ghost.org/integrations/comments?no-cache=1
2. Try clicking on any docs link and nothing will happen
3. Note there are errors in the dev tools console

<img width="1245" alt="screenshot 2018-11-16 at 12 24 03" src="https://user-images.githubusercontent.com/415/48621241-d013e400-e99a-11e8-94ec-9eb7dc2c08c0.png">

**Comment by aileen** [comment]
@kevinansfield I am not able to reproduce this. Are you still able to?

**Comment by aileen** [comment]
Note, there were some bug fixes in the ServiceWorker plugin. Might've resolved this issue maybe...

**Comment by kevinansfield** [comment]
I can't reproduce any more either 🎉
