### ISSUE TITLE
Images showing as code samples in migration API doc

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/docs-old#45]
### Issue Summary

In the Troubleshooting section of the migration API docs there are two code samples shown but it looks like these should be images?

<img width="668" alt="screenshot 2018-11-20 at 14 37 06" src="https://user-images.githubusercontent.com/415/48780422-c3acc580-ecd1-11e8-8aca-ac966492d831.png">

### To Reproduce

1. Open https://docs.ghost.org/api/migration/#troubleshooting

**Comment by kymellis** [comment]
@JohnONolan I believe you migrated these API docs - can you take a look at Kevin's comments and confirm if these code samples are meant to be images instead?

**Comment by JohnONolan** [comment]
yes kevin is right, you can see by opening the image urls in the codeblock, ^ that one above is:

![e56ea53-screenshot2017-06-06at18 48 05](https://user-images.githubusercontent.com/120485/48823438-6da05680-ed93-11e8-93ec-148c9e304ef8.png)
