### ISSUE TITLE
Subscribers template override info difficult to spot

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/docs-old#49]
### Issue Summary

Trying to answer [this forum topic](https://forum.ghost.org/t/how-to-change-the-copy-on-the-subscribe-page/4308) I went looking for the info about template overrides but at first I thought it had been removed. I did eventually find a couple of references to overrides on the [subscribers theme doc](https://docs.ghost.org/api/handlebars-themes/subscribers) but they were well hidden and assumed knowledge about where to find the default templates.

**Comment by kymellis** [comment]
@kevinansfield most of the info is on the page but it's quite spread out, and there's no links to the templates. I've submitted a PR that includes a new section about overriding the default themes + links.
