### ISSUE TITLE
Need help: Error: GHOST_API_URL and GHOST_API_KEY are required to build

### ISSUE THREAD

**Issue by ashokballolli** [TryGhost/docs-old#55]
Hi, 

Need help in resolving this error.

Followed all these steps
1. git clone this repo & cd into it as usual
2. npm install --global gatsby-cli to install Gatsby
3. yarn to install top-level dependencies.
4. Copy .env.example to .env.development

gatsby develop : No Issues
gatsby build: Getting error 
```
error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.


  Error: GHOST_API_URL and GHOST_API_KEY are required to build. Check the CONTRIBUTING guide.
```
Not sure what i am missing here! 
Looking for help to resolve this issue. 

Other details:
➜ node -v
v11.6.0
➜ npm -v
6.5.0
➜ gatsby -v
2.4.8

Thanks in advance.

**Comment by ashokballolli** [comment]
Sorry, this has been resolved. forgot to create .env.production.

**Comment by Muzzamil75** [comment]
I am facing same issue but cant able to resolve this still after making env.production and copy pasting the code ! Help me out

**Comment by Muzzamil75** [comment]
help mee plzzzzzzzzzzzzzzzzzzzz
