### ISSUE TITLE
Add script to wrap <table> elements in <div>

### ISSUE THREAD

**Issue by aileen** [TryGhost/docs-old#63]
To enable horizontal scrolling for tables that are rendered from a Ghost post source, we need to add a `<div>` wrapper for those `<table>` elements, due to a [flexbox bug](https://stackoverflow.com/questions/25626157/why-does-not-displayblock-and-100-width-work-on-table-rows).

The probably easiest way to do so, is to use the `gatsby-browser` API.

**Comment by JohnONolan** [comment]
This is not a priority.
