### ISSUE TITLE
Expand e2e test and setup for continuous integration

### ISSUE THREAD

**Issue by aileen** [TryGhost/docs-old#69]
The current e2e test is covering almost all important parts already, but can be improved to include the testing of the TOC scroll behaviour.

Furthermore, we should implement continuous integration for the e2e test.

### Todos:
- [ ] implement TOC scroll behaviour test
- [ ] implement continuous integration

**Comment by JohnONolan** [comment]
We don't need a test for TOC scroll, and we dont need CI for a single test - this is not validated
