### ISSUE TITLE
[Readme] Add docs on building algolia search index 

### ISSUE THREAD

**Issue by dcworldwide** [TryGhost/docs-old#85]
How can contributors build an algolia search index?

I have a test algoilia site, i've set the instance id, admin api key, but the index is never populated.

**Comment by dcworldwide** [comment]
Ive also set the algolia env var to true but not luck. Any ideas?

**Comment by JohnONolan** [comment]
Contributors cannot build an algolia search index for our docs - this is not a bug :)

**Comment by dcworldwide** [comment]
I figured it out.
