### ISSUE TITLE
Admin Api Docs have several problems

### ISSUE THREAD

**Issue by dshook** [TryGhost/docs-old#96]
Problem 1:
Docs are not clear at all about what permissions the token integrations have vs the User Authentication method.

Problem 2:
The URL in the [creating a session](https://docs.ghost.org/api/admin/#creating-a-session) is wrong. It says `POST /sessions/` but it's actually `/admin/session/` (especially note the ending s)

Problem 3:
The `/session/` endpoint requires an Origin or Referrer but doesn't mention it in the docs, otherwise you get the error: 'Could not determine origin of request. Please ensure an Origin or Referrer header is present.'

Problem 4:
The body of the [creating a post](https://docs.ghost.org/api/admin/#creating-a-post) is wrong. It uses the key `post` when it's actually `posts`

It's very frustrating when you have to constantly second guess the docs!

**Comment by ErisDS** [comment]
Hi @dshook thanks for taking the time to point out these issues. The docs are still very much WIP, and I really appreciate getting a bit of feedback. 

I've pushed out changes to cover all 4 points. For 1 and 3, the trickier ones, there has been quite significant additions to the authentication section. 

Really hope that this covers the immediate issues. It's still WIP tho 😬
